_pages/landing-page.html

Updated Early-bird t-shirt dates

:pencil: Updated Sponsorship Prospectus

---

_pages/about.html

Related to #13: Can check off all in `About` heading 
Will need to update dates once we have them, but this lets us release the site before we have formal dates nailed down.

:pencil: Copy changes

---

_pages/room-sharing.md

Related to #13, checks boxes for room and ride sharing. 
Deleted the tables because I think the spreadsheet is pretty self-explanatory and it contains examples already.

:pencil: Edit room share info

---

README.md

- Updates the CoC to link to the local `CODE_OF_CONDUCT.md` file
- Small formatting changes to make it easier to read 
- Currently working on `develop` so updated that 
cc @KatherineMichel, feedback welcome!

:pencil: Readme edits

---

_pages/speaking-resources.md

- Update @ossanna16's email and bio per her email!

:pencil: Update Anna’s bio/email per her email

---

_layouts/home.html
_pages/financial-aid.md
_pages/speaking.md

Realized I read the date wrong!
- Change June 4 to June 3. 
- Comment in deadline paragraph on financial aid page

:ambulance: Fix dates

---

_pages/conduct.html

Closes #13
- Add phone number for accessing San Diego 911 from outside San Diego or from a cell phone 
@KatherineMichel I looked through #13 and the organizers' placeholders have been updated. The only check left is to check with local organizers to see if anything was missed. So I think this PR can close that ticket and we can create new tickets for further content updates?

:pencil: Add outside of SD access to 911 number

---

_pages/venue.html

Added accessibility info. Fixes part of issue #71

Updated venue info

---

_pages/financial-aid.md

Closes #94 .
- Add financial aid email sentence to financial aid page

:pencil: Add financial aid email

---

_pages/speaking-resources.md

Portia volunteered via Twitter DM to me
- Add Portia Burton as a speaker mentor

:pencil: Add a new speaker mentor

---

_config.yml
_includes/nav.html
_pages/faqs.html
_pages/tickets.html
_posts/2018-04-27-tickets-on-sale.md

- Add tickets on sale blog post 
- Update tickets page 
- Update FAQ page 
- Add tickets link to config 
- Update header text for ticket link
Please do not merge until tickets page on tito is live.

WIP Tickets on sale

---

_pages/venue.html

Create a map of meetings around the hotel. Ensure email for contact still works.
Closes #28

Update recovery meetings block.

---

_includes/sponsor-footer.html
_pages/colophon.md
_pages/sponsors.html

Closes #115 
-From request from @daheats, adding Community sponsors heading.
-

Adding community sponsor heading

---

_sponsors/2018-07-21-jbssolutions.md

Adding JBS description and logo

Adding JBS Silver Sponsor

---

_posts/2018-07-24-tutorials-announcement.md

- Fixes link to image. Underscore vs hyphen, doh!

Changes link to image

---

_pages/venue.html

- Add note about contacting us if hotel appears sold out (per yesterday's meeting) 
- Delete commented code 
- Add heated pool!

:pencil: Add hotel booking note; clean up comments

---

_pages/schedule.html

- Replaces TBD tutorial pricing with actual price 
- Adds link to buy tickets

:pencil: Add tutorial pricing and link to buy tickets

---

_posts/2018-07-17-announcing-our-program.md
_schedule/talks/2018-10-16-11-30-t0-simpl-framework-big-impact.md

:pencil: SIMPL —> Simpl

---

_schedule/talks/2018-10-17-14-10-t1-unique-ways-to-hack-into-a-python-web.md

Updating Tilak's Twitter link

---

_includes/nav.html

- Remove "early bird pricing available" note, as EB tickets are sold out.

:fire: Remove early bird pricing

---

_sponsors/2018-08-20-caktus-group.md

Caktus Group Logo & Description

---

_schedule/talks/2018-10-17-11-30-t0-django-rest-framework-moving-past-the-to.md

- Add my GitHub link
- Add a missing `in` to my bio
- Convert my talk description into paragraph form to make it easier for people to skim through

Update Drew's DRF talk

---

_schedule/talks/2018-10-15-17-00-t0-packaging-django-apps-for-distribution.md

Closes # N/A
- I started a new job at Datadog last week, so I am adding it to my bio.

adds new job to my bio

---

_posts/2018-09-17-JBSIntro.md

Reused from last year per Adam Fast

JBS Blog 1

---

_pages/speaking-resources.md

This clarifies why dark text on a light background works best.

Change "projector" to "projection screen."

---

_posts/2018-09-24-orientation.md

I has no picture, so I just left it out. Let me know if I need any changes.

added Orientation blog post

---

_schedule/talks/2018-10-16-15-10-t1-one-engineer-an-api-and-an-mvp-or-how-i.md

Closes # .
-Removes full outline of talk content; there's too much detail
-

Shorten description to teaser

---

_schedule/talks/2018-10-15-17-30-t0-it-s-about-time.md
_schedule/talks/2018-10-15-17-30-t1-becoming-a-multilingual-superhero-in.md

- Changes Monday last talk time from 5:40 to 5:30

:ambulance: Fix Monday last talk time (5:40 —> 5:30)

---

_schedule/talks/2018-10-16-18-00-board-game-night.md

:newspaper: Add board game night

---

_pages/tickets.html

Based on feedback from an attendee

Cancellation fee applies to tutorials as well

---

_schedule/talks/2018-10-15-09-00-orientation.md

added Orientation details to schedule

---

_pages/speaking-resources.md
_schedule/talks/2018-10-17-15-10-t0-orm-the-sequel.md

My details were a bit out of date on the website. This PR fixes that.

Update Katie's details

---

_posts/2018-10-03-sprints-intro.md

Sprints Intro/Attendee blog post

---

_posts/2018-10-03-lincoln-loop.md

fixed typo

---

_includes/schedule-session-full.html
_includes/schedule-session.html
_layouts/session-details.html
_pages/organizers.html

:art: Adds support for personal pronouns

---

_posts/2018-10-03-sprints-intro.md

added mention of FLOSS tutorial

---

_posts/2018-10-09-sprint-organizers.md

I was wondering why this wasn't showing up...
Closes # .
-
-

Fixed date stamp

---

_posts/2018-10-11-git-help-desk.md

Adds info about intro to open source

Add info about intro to open source

---

_schedule/talks/2018-10-16-10-00-your-web-framework-needs-you.md

Sorry. I just noticed these two (and you were a big quick for me @jefftriplett! 🙂)

Fixed typos on `your-web-framework-needs-you`.

---

_includes/nav.html
_pages/faqs.html

- Edit ticket button on homepage to reflect sprints/tutorials on sale 
- Edit FAQs to reflect conference tickets sold out

:pencil: Edit ticket button

---

_pages/speaking-resources.md
_pages/venue.html

- Adds green room and quiet room to speaker resources page 
- Adds quiet room to venue accessibility page

:pencil: Add green room and quiet room

---

_schedule/talks/2018-10-15-12-50-t0-lightning-talks.md
_schedule/talks/2018-10-16-12-50-t0-lightning-talks.md
_schedule/talks/2018-10-17-12-50-t0-lightning-talks.md

Lightning Talk schedule updates

---

_includes/nav.html

Remove tutorial tickets from button

:pencil: Update button
